DELETE http://localhost:3003/api/blogs/64d435177a0cdcf4805314b2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlcGEiLCJpZCI6IjY0ZDNiNzI1MDZhZGViNGIyODA0OTI3ZCIsImlhdCI6MTY5MTYyODc4NiwiZXhwIjoxNjkxNjI5Njg2fQ.KSEsCkIifjckN8Kq04tBaVa1xXNSPeIKijP7Bj69fGg